apiVersion: v1
kind: PersistentVolume
metadata:
  name: prysm-beacon-pv4
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: do-block-storage
  hostPath:
    path: /mnt/data/prysm4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prysm-beacon-data-pvc4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prysm-beacon
  labels:
    app: prysm-beacon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prysm-beacon
  template:
    metadata:
      labels:
        app: prysm-beacon
    spec:
      containers:
      - name: prysm-beacon
        image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
        args:
          [
            "--sepolia",
            "--force-clear-db",
            "--datadir=/data2",
            "--min-sync-peers=3",
            "--jwt-secret=/jwtsecret/jwtsecret",
            "--execution-endpoint=http://geth-mainnet-full:8551",
            "--rpc-host=0.0.0.0",
            "--accept-terms-of-use",
            "--checkpoint-sync-url=https://sepolia.beaconstate.info",
            "--genesis-beacon-api-url=https://sepolia.beaconstate.info"
          ]
        ports:
        - containerPort: 13000
          name: p2p
          protocol: TCP
        - containerPort: 4000
          name: grpc
          protocol: TCP
        volumeMounts:
        - name: prysm-beacon-pv4
          mountPath: /data2
        - name: jwtsecret
          mountPath: /jwtsecret
        - name: validator-keys
          mountPath: /data/validator_keys
          readOnly: true
      - name: busybox
        image: busybox
        command: ["sh", "-c", "while true; do sleep 3600; done"]
      volumes:
      - name: prysm-beacon-pv4
        persistentVolumeClaim:
          claimName: prysm-beacon-data-pvc4
      - name: jwtsecret
        secret:
          secretName: jwtsecret
      - name: validator-keys
        secret:
          secretName: validator-keys
---
apiVersion: v1
kind: Service
metadata:
  name: prysm-beacon
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 4000
    targetPort: 4000
  - name: p2p
    port: 13000
    targetPort: 13000
  selector:
    app: prysm-beacon

